### PR TITLE
feat: add CN validation

### PR DESCRIPTION
**Pull request by alex-reiff**
### Description

issue: https://github.ibm.com/GoldenEye/issues/issues/9345

Add validation that the common names for root and intermediate CA are different.

Would be nice to also remove the default for intermediate CA so consumers know to set two different values, but that would be a breaking change.

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by alex-reiff** [comment]
skipping upgrade test as the change to the example is a field which forces replacement:
```
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185: -/+ resource "ibm_sm_private_certificate_configuration_root_ca" "private_certificate_root_ca" {
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       ~ common_name                       = "cloud.ibm.com" -> "*.cloud.ibm.com" # forces replacement
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       + config_type                       = (known after apply)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       ~ country                           = [] -> (known after apply)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       ~ created_at                        = "2024-05-30T15:10:44Z" -> (known after apply)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       ~ created_by                        = "IBMid-666000KAO3" -> (known after apply)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       ~ crl_expiry                        = "259200s" -> (known after apply)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       ~ crl_expiry_seconds                = 259200 -> (known after apply)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       ~ data                              = (sensitive value)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       ~ expiration_date                   = "2025-05-30T15:10:44Z" -> (known after apply)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       ~ id                                = "ca-tor/df533632-be44-49c6-9a75-78b7e899f1fe/root-ca" -> (known after apply)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       ~ key_bits                          = 2048 -> (known after apply)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       ~ locality                          = [] -> (known after apply)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       ~ max_path_length                   = -1 -> (known after apply)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       ~ max_ttl_seconds                   = 31536000 -> (known after apply)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:         name                              = "root-ca"
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       ~ organization                      = [] -> (known after apply)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       ~ other_sans                        = [] -> (known after apply)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       ~ ou                                = [] -> (known after apply)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       ~ permitted_dns_domains             = [] -> (known after apply)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       ~ postal_code                       = [] -> (known after apply)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       ~ province                          = [] -> (known after apply)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       ~ secret_type                       = "private_cert" -> (known after apply)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       ~ serial_number                     = "54:a6:90:05:c4:a9:2f:f6:09:2c:ca:01:79:11:aa:73:a0:fa:0d:1c" -> (known after apply)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       ~ status                            = "configured" -> (known after apply)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       ~ street_address                    = [] -> (known after apply)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       + ttl                               = (known after apply)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       ~ ttl_seconds                       = 31536000 -> (known after apply)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:       ~ updated_at                        = "2024-05-30T15:10:44Z" -> (known after apply)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:         # (11 unchanged attributes hidden)
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185:     }
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185: 
TestRunUpgradeExample 2024-05-30T15:11:02Z command.go:185: Plan: 1 to add, 0 to change, 1 to destroy.
```

**Comment by shemau** [comment]
The new test is causing the schematics test to fail because the two values are the same.

```
 2024/06/21 14:33:54 Terraform plan |   on ../../main.tf line 12, in locals:
 2024/06/21 14:33:54 Terraform plan |   12:   common_name_validate_check = regex("^${local.common_name_validate_msg}$", (!local.common_name_validate_condition ? local.common_name_validate_msg : ""))
 2024/06/21 14:33:54 Terraform plan |     ├────────────────
 2024/06/21 14:33:54 Terraform plan |     │ while calling regex(pattern, string)
 2024/06/21 14:33:54 Terraform plan |     │ local.common_name_validate_condition is true
 2024/06/21 14:33:54 Terraform plan |     │ local.common_name_validate_msg is "The values for 'root_ca_common_name' and 'intermediate_ca_common_name' must be different"
 2024/06/21 14:33:54 Terraform plan | 
 2024/06/21 14:33:54 Terraform plan | Call to function "regex" failed: pattern did not match any part of the given
 2024/06/21 14:33:54 Terraform plan | string.
 ```
 
 The cause is that the private example hard codes the root CA CN to "cloud.ibm.com" and the does not pass the intermediate CA CN. The default value for intermediate CA CN is also "cloud.ibm.com".
 
 So examples/private/main.tf requires the same change that went into examples/default.

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
